### ISSUE TITLE
EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by praneethkumarpidugu** [assist-software/python-django-exporting-files#1]
Hi,
       I tried to install requirements.txt but I got the following traceback
Requirement already satisfied (use --upgrade to upgrade): Django==1.8.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 2))
  Downloading MySQL-python-1.2.5.zip (108kB)
    100% |################################| 110kB 841kB/s           
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-d7FZTz/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-d7FZTz/MySQL-python/setup.py", line 17, in <module>
    
        metadata, options = get_config()
    
      File "setup_posix.py", line 43, in get_config
    
        libs = mysql_config("libs_r")
    
      File "setup_posix.py", line 25, in mysql_config
    
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d7FZTz/MySQL-python

Does it require any particular python version like 2.7 or 3.4 ?

**Comment by praneethkumarpidugu** [comment]
I found the issue: it looks like mysql_config is missing.. I crawled through stackoverflow to find similar issue and found this link http://stackoverflow.com/a/5178698/4325513
I just installed:  sudo apt-get install libmysqlclient-dev
then I proceeded into install: sudo pip install MySQL-python==1.2.5
And it worked!
